# Generated by Django 6.0.6 on 2026-07-06 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('last_date', models.DateField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma')], default='undergraduate', max_length=20)),
                ('duration', models.CharField(blank=True, default='4 Years', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('seats', models.IntegerField(default=0)),
                ('fee_per_semester', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
