# Generated by Codex on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionapplication'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='admissionapplication',
            name='admissions__status_bc83ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='admissionapplication',
            name='admissions__program_74d7ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='admissionapplication',
            name='admissions__preferr_0d2411_idx',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='status',
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['-obtained_marks'], name='admissions__obtaine_7a9efd_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['program'], name='admissions__program_4fead5_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['preferred_department'], name='admissions__preferr_32d6b8_idx'),
        ),
    ]
