# Generated by Codex on 2026-07-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_remove_admission_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionApplication',
        ),
    ]
