# Generated by Django 5.2.1 on 2026-07-18 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_delete_admission_application'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='level',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('two_year', 'Two Year Program'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('short_course', 'Short Course')], default='undergraduate', max_length=20),
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('cnic_or_bform', models.CharField(max_length=20, verbose_name='CNIC/B-Form')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/')),
                ('previous_school', models.CharField(blank=True, max_length=250)),
                ('board_or_university', models.CharField(blank=True, max_length=200)),
                ('obtained_marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_marks', models.PositiveIntegerField(default=1100, validators=[django.core.validators.MinValueValidator(1)])),
                ('merit_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('preferred_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='departments.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.academicprogram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='admissions__status_283f48_idx'), models.Index(fields=['program', 'status'], name='admissions__program_74d7ee_idx'), models.Index(fields=['cnic_or_bform'], name='admissions__cnic_or_0bd6ec_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('obtained_marks__lte', models.F('total_marks'))), name='admission_marks_not_above_total_v2')],
            },
        ),
    ]
