# Generated by Django 6.0.6 on 2026-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('mp4', 'Direct MP4')], default='youtube', max_length=10)),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbs/')),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('button_link', models.CharField(blank=True, default='#', max_length=200)),
                ('button2_text', models.CharField(blank=True, max_length=100)),
                ('button2_link', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Principal', max_length=200)),
                ('designation', models.CharField(default='Principal, GCMS D.I. Khan', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('message', models.TextField()),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Principal's Message",
                'verbose_name_plural': "Principal's Message",
            },
        ),
    ]
